services:
  backend:
    image: ${IMAGE_PREFIX}/clouder-backend:latest
    container_name: clouder-backend-prod
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: ${IMAGE_PREFIX}/clouder-frontend:latest
    container_name: clouder-frontend-prod
    environment:
      - VITE_API_BASE_URL=/api
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: clouder-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  logs:
