name: Deploy to Production

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/clouder-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/clouder-frontend:latest

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        env:
          IMAGE_PREFIX: ${{ env.IMAGE_PREFIX }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          envs: IMAGE_PREFIX,SPOTIFY_CLIENT_ID,SPOTIFY_CLIENT_SECRET,SPOTIFY_REDIRECT_URI,MONGO_URL,MONGO_DB,FRONTEND_URL,CORS_ALLOWED_ORIGINS
          script: |
            cd ${{ secrets.PROD_PATH }}
            git pull
            cat <<EOF > backend/.env
            SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
            SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
            SPOTIFY_REDIRECT_URI=$SPOTIFY_REDIRECT_URI
            FRONTEND_URL=$FRONTEND_URL
            CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
            MONGO_URL=$MONGO_URL
            MONGO_DB=$MONGO_DB
            EOF
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
